---
- name: Install docker
  yum:
    name: docker
    state: present
  become: yes

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add user to group
  user:
    name: "{{ docker_user }}"
    comment: "{{ docker_comment }}"
    group: "{{ docker_group }}"
  become: yes




